config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  resources :articles do
    resources :article_histories
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :article_histories, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/article_history.rb
class ArticleHistory < ApplicationRecord
  belongs_to :article
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/article_histories_controller.rb
class ArticleHistoriesController < ApplicationController
  def index
    @article_histories = ArticleHistory.where(article_id: params[:article_id] ,is_deleted: false).order(created_at: :desc)
  end

  def show
  end

  def destroy
    @article = Article.find(params[:article_id])
    @article_histories = @article.article_histories.find(params[:id])
    @article_histories.is_deleted = true
    @article_histories.deleted_at = Time.now
    @article_histories.save
    redirect_to article_article_histories_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.where(is_deleted: false)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article_history = @article.article_histories.create(
      title: @article.title,
      body: @article.body,
      author: @article.author,
    )
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.is_deleted = true
    @article.deleted_at = Time.now
    @article.save

    redirect_to root_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :author, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
  def destroy
    @article = Article.find(params[:article_id])
    @comment = Comment.find(params[:id])
    @comment.is_deleted = true
    @comment.deleted_at = Time.now
    @comment.save
    redirect_to article_path(@article)
  end
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_histories_helper.rb
module ArticleHistoriesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/article_histories/index.html.erb
<h1>ArticleHistories</h1>
<table>
  <tr>
    <th></th>
    <th>Title</th>
    <th>Author</th>
    <th>Body</th>
    <th>Created At</th>
    <th>Updated At</th>
    <th>Deleted</th>
    <th>Action</th>
  </tr>
  <%
    i = 1 
    @article_histories.each do |article_history|
  %>
  <tr>
    <td><%= i %></td>
    <td><%= article_history.title %></td>
    <td><%= article_history.author %></td>
    <td><%=
      if article_history.body.length > 40
        truncate(article_history.body, length: 40)
      else
        article_history.body
      end 
    %></td>
    <td><%= article_history.created_at %></td>
    <td><%= article_history.updated_at %></td>
    <td><%= article_history.is_deleted %></td>
    <td><%= link_to "delete", article_article_history_path(id: article_history.id),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></td>
  </tr>
  <% 
  i += 1
  end
  %>
</table>

app/views/article_histories/show.html.erb
<h1>ArticleHistories#show</h1>
<p>Find me in app/views/article_histories/show.html.erb</p>

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :author %><br>
    <%= form.text_field :author %><br>
    <% article.errors.full_messages_for(:author).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
    </li>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<h3>by <%= @article.author %></h3>
<p><%= @article.body %></p>

<ul>
  <li><%= link_to "History", article_article_histories_path(@article) %></li>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<% if (comment.is_deleted == false) %>
<p>
  <strong>by <%= comment.commenter %>: </strong>
  <%= comment.body %>
  <%= link_to "delete" , article_comment_path(article_id: @article.id, id: comment.id),
                  method: :delete,
                  data: { confirm: "Are you sure?" }%>
  <br />
  <%= comment.created_at %>
</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechnicalQuestionTwo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>